import sharp from 'sharp';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

// Get directory name in ESM context
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export async function applyWatermark(
  imageBuffer: Buffer,
  shouldWatermark: boolean,
  appName: string = 'Khuyoot'
): Promise<Buffer> {
  if (!shouldWatermark) return imageBuffer;

  try {
    // Get main image metadata to calculate positions
    const metadata = await sharp(imageBuffer).metadata();
    const width = metadata.width || 1024;
    const height = metadata.height || 1024;

    console.log(`[Watermark] Applying to ${width}x${height} image`);

    // Create text watermark (SVG) for bottom-left
    const fontSize = Math.max(16, Math.floor(width / 40)); // Responsive font size
    const svgText = `
      <svg width="${width}" height="${height}">
        <defs>
          <style>
            .watermark-text {
              fill: white;
              font-size: ${fontSize}px;
              font-weight: 600;
              opacity: 0.5;
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
              text-anchor: start;
            }
          </style>
        </defs>
        <text x="20" y="${height - 20}" class="watermark-text">Generated by ${appName}</text>
      </svg>`;

    // Try to load main logo - check multiple possible paths
    let logoPath = path.resolve(__dirname, '../../public/logo.png');
    let hasLogo = fs.existsSync(logoPath);

    if (!hasLogo) {
      // Fallback to PWA icon
      logoPath = path.resolve(__dirname, '../../public/icons/icon-192.png');
      hasLogo = fs.existsSync(logoPath);
    }

    if (!hasLogo) {
      // Fallback to icon folder
      logoPath = path.resolve(__dirname, '../../public/icons/icon-192.png');
      hasLogo = fs.existsSync(logoPath);
    }

    console.log(`[Watermark] Logo path: ${logoPath}`);
    console.log(`[Watermark] Logo exists: ${hasLogo}`);

    // Build the list of layers to composite
    const layers: any[] = [
      {
        input: Buffer.from(svgText),
        top: 0,
        left: 0,
      },
    ];

    // Add logo if it exists
    if (hasLogo) {
      try {
        const logoMeta = await sharp(logoPath).metadata();
        const logoWidth = Math.floor(width * 0.25); // Logo is ~25% of image width
        const logoHeight = logoMeta.height 
          ? Math.floor((logoWidth * logoMeta.height) / (logoMeta.width || 1)) 
          : logoWidth;

        console.log(`[Watermark] Logo dimensions: ${logoWidth}x${logoHeight}`);

        const logoBuffer = await sharp(logoPath)
          .resize(logoWidth, logoHeight, { 
            fit: 'contain', 
            background: { r: 0, g: 0, b: 0, alpha: 0 } 
          })
          .toBuffer();

        // Calculate bottom-right position with 20px padding
        layers.push({
          input: logoBuffer,
          top: height - logoHeight - 20,
          left: width - logoWidth - 20,
        });
      } catch (logoErr) {
        console.warn('[Watermark] Failed to prepare logo:', (logoErr as Error).message);
      }
    }

    // Single pass composition
    const result = await sharp(imageBuffer)
      .composite(layers)
      .jpeg({ quality: 90, mozjpeg: true })
      .toBuffer();
      
    console.log(`[Watermark] Applied successfully (${(result.length / 1024).toFixed(1)} KB)`);
    return result;
  } catch (err) {
    console.error('[Watermark] Error applying watermark:', err);
    // Return original image if watermark fails
    return imageBuffer;
  }
}
