import sharp from 'sharp';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

// Get directory name in ESM context
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export async function applyWatermark(
  imageBuffer: Buffer,
  shouldWatermark: boolean,
  appName: string = 'Khuyoot'
): Promise<Buffer> {
  if (!shouldWatermark) return imageBuffer;

  try {
    // Get main image metadata to calculate positions
    const metadata = await sharp(imageBuffer).metadata();
    const width = metadata.width || 1024;
    const height = metadata.height || 1024;

    console.log(`[Watermark] Applying to ${width}x${height} image`);

    // Create text watermark (SVG) for bottom-left
    const fontSize = Math.max(16, Math.floor(width / 40)); // Responsive font size
    const svgText = `
      <svg width="${width}" height="${height}">
        <defs>
          <style>
            .watermark-text {
              fill: white;
              font-size: ${fontSize}px;
              font-weight: 600;
              opacity: 0.5;
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
              text-anchor: start;
            }
          </style>
        </defs>
        <text x="20" y="${height - 20}" class="watermark-text">Generated by ${appName}</text>
      </svg>`;

    // Try to load logo - check multiple possible paths
    let logoPath = path.resolve(__dirname, '../../public/pwa-192x192.svg');
    let hasLogo = fs.existsSync(logoPath);

    if (!hasLogo) {
      // Fallback to og-image.png
      logoPath = path.resolve(__dirname, '../../public/og-image.png');
      hasLogo = fs.existsSync(logoPath);
    }

    if (!hasLogo) {
      // Fallback to favicon
      logoPath = path.resolve(__dirname, '../../public/icons/icon-192.png');
      hasLogo = fs.existsSync(logoPath);
    }

    console.log(`[Watermark] Logo path: ${logoPath}`);
    console.log(`[Watermark] Logo exists: ${hasLogo}`);

    // Composite watermark onto image
    let composited = sharp(imageBuffer).composite([
      {
        input: Buffer.from(svgText),
        top: 0,
        left: 0,
      },
    ]);

    // Add logo if it exists
    if (hasLogo) {
      try {
        const logoMeta = await sharp(logoPath).metadata();
        const logoWidth = Math.floor(width * 0.1); // Logo is ~10% of image width
        const logoHeight = logoMeta.height ? Math.floor((logoMeta.width || 1) > 0 ? (logoWidth * logoMeta.height) / (logoMeta.width || 1) : logoWidth) : logoWidth;

        console.log(`[Watermark] Logo dimensions: ${logoWidth}x${logoHeight}`);

        composited = composited.composite([
          {
            input: await sharp(logoPath)
              .resize(logoWidth, logoHeight, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
              .toBuffer(),
            gravity: 'southeast',
            offset: { left: 20, top: 20 },
          },
        ]);
      } catch (logoErr) {
        console.warn('[Watermark] Failed to composite logo:', (logoErr as Error).message);
      }
    }

    const result = await composited.toBuffer();
    console.log(`[Watermark] Applied successfully (${(result.length / 1024).toFixed(1)} KB)`);
    return result;
  } catch (err) {
    console.error('[Watermark] Error applying watermark:', err);
    // Return original image if watermark fails
    return imageBuffer;
  }
}
